export default [
    {
      name: 'Barbarian',
      id: 1,
      class_bonus: ['Str', 'Con'],
      backgrounds: ['Clan champion', 'Caravan outrider', 'Fur trapper', 'Mountain tribeswoman', 'Wasteland survivalist', 'Gladiator'],
      base_hp: 7,
      base_ac: 12, 
      base_pd: 11,
      base_md: 10,
      background_points: 8,
      recovery_dice: "d10-/lvl",
      starting_gold: "25gp OR 1d6 x 10gp",
    },
    {
      name: 'Bard',
      id: 2,
      class_bonus: ['Dex', 'Cha'],
      backgrounds: ['Wandering minstrel', 'Cathedral musician', 'Court jester', 'Mercenary', 'Tavern owner', 'Failed hedge wizard', 'Diplomat', 
            'Spy', 'Royal taster', 'Caravan guide', 'Smuggler', 'Battle skald'],
      base_hp: 7,
      base_ac: 12,
      base_pd: 10,
      base_md: 11,
      background_points: 8,
      recovery_dice: "d8-/lvl",
      starting_gold: "25gp OR 1d6 x 10gp",
    },
    {
      name: 'Cleric',
      id: 3,
      class_bonus: ['Wis', 'Str'],
        backgrounds: ['Healer', 'Archivist', 'Military chaplain', 'Temple guard', 'Bartender', 'Reformed thief', 'Dwarven hierophant',
            'Initiate', 'Bishop'],
      base_hp: 7,
      base_ac: 14,
      base_pd: 11,
      base_md: 11,
      background_points: 8,
      recovery_dice: "d8-/lvl",
      starting_gold: "25gp OR 1d6 x 10gp",
    },
    {
      name: 'Fighter',
      id: 4,
      class_bonus: ['Str', 'Con'],
      backgrounds: ['Swordmaster', 'Mercenary captain', 'Sea raider', 'Shieldwall spearman', 'Explorer', 'Bouncer', 'Thug', 'City guardsman', 
            'Former gladiator', 'Former orc captive', 'Bankrupt nobleman', 'Duelist', 'Goblin-hunter'],
      base_hp: 8,
      base_ac: 15,
      base_pd: 10,
      base_md: 10,
      background_points: 8,
      recovery_dice: "d10-/lvl",
      starting_gold: "25gp OR 1d6 x 10gp",
    },
    {
      name: 'Paladin',
      id: 5,
      class_bonus: ['Str', 'Cha'],
      backgrounds: ['City guardsman', 'Combat medic', 'Bodyguard', 'Outlaw hunter', 'Inquisitor'],
      base_hp: 8,
      base_ac: 16,
      base_pd: 10,
      base_md: 12,
      background_points: 8,
      recovery_dice: "d10-/lvl",
      starting_gold: "25gp OR 1d6 x 10gp",
    },
    {
      name: 'Ranger',
      id: 6,
      class_bonus: ['Dex', 'Str'],
      backgrounds: ['Tracker', 'Bounty hunter', 'Beast slayer', 'Woodsy assassin', 'Orc slayer', 'Wanderer'],
      base_hp: 7,
      base_ac: 14,
      base_pd: 11,
      base_md: 10,
      background_points: 8,
      recovery_dice: "d8-/lvl",
      starting_gold: "25gp OR 1d6 x 10gp",
    },
    {
      name: 'Rogue',
      id: 7,
      class_bonus: ['Dex', 'Cha'],
        backgrounds: ['Street thug', 'Cat burglar', 'Diplomat', 'Professional gambler', 'Courtier', 'Jewel thief',
        'Acrobat', 'Con artist', 'Bartender', 'Spy master', 'Pirate', 'Dandy', 'Rat catcher'],
      base_hp: 6,
      base_ac: 12,
      base_pd: 12,
      base_md: 10,
      background_points: 8,
      recovery_dice: "d8-/lvl",
      starting_gold: "25gp OR 1d6 x 10gp",
    },
    {
      name: 'Sorcerer',
      id: 8,
      class_bonus: ['Cha', 'Con'],
      backgrounds: ['Tribal shaman', 'Pirate captain', 'Spell-arena gladiator', 'Failed wizard', 'Sahuagin hunter'],
      base_hp: 6,
      base_ac: 10,
      base_pd: 11,
      base_md: 10,
      background_points: 8,
      recovery_dice: "d6-/lvl",
      starting_gold: "25gp OR 1d6 x 10gp",
    },
    {
      name: 'Wizard',
      id: 9,
      class_bonus: ['Int', 'Wis'],
      backgrounds: ['Magical prodigy', 'Spell thief', 'Hedge wizard', 'Transformed familiar', 'Ship\'s wizard', 'Royal poisnoner'],
      base_hp: 6,
      base_ac: 10,
      base_pd: 10,
      base_md: 12,
      background_points: 8,
      recovery_dice: "d6-/lvl",
      starting_gold: "25gp OR 1d6 x 10gp",
    }
  ];
  